### ISSUE TITLE
make provisioning of machines less work

### ISSUE THREAD

**Issue by job** [NLNOG/nlnog-ring#27]
We require a db backend for this, habbie has already written some python to help in that space

Current steps are 
- check machine cpu (64 bit?)
- check ubuntu distribution
- check v6 connectivity and configuration (should be static)
- add CNAME in DNS on job's private server
- add machine to /etc/puppet/files/etc/hosts so master can create smokeping configs and not error
- add ring repo and apt-get update
- puppetd --test
- apt-get update
- puppetd --test a few times
- add machine to ring.nlnog.net txt record
- add owner to admin group
- add news item on ring.nlnog.net
- notify participant they can subscribe to mailman
- manually type email to participant to welcome them
- manually type email to ring-users@ to announce the new node
- notify teun a new node has arrived and he should add it to map

this should be easier...

**Comment by teunvink** [comment]
obsoleted, closing this.
