### ISSUE TITLE
ring-change-sshkeys

### ISSUE THREAD

**Issue by job** [NLNOG/nlnog-ring#43]
Some kind of wrapper that can manage the sshkeys for users would be nice. I imagine the following: 

user types ring-change-sshkeys on a ring-node, and it will open up the preferred editor and it should like like typing 'crontab -e'. 

The first few lines of the authorized_keys file that is displayed should be some comments which contain warnings and what the file means. 

The user can then edit the file to it's liking and when quiting the editor the resulting data should be validated:
- empty file is error
- invalid keys error
- etc

If an error is found the user should be presented with a choice: discard all changes or open the editor again. 

If the file is valid, it can be emailed to ring-admins@ in puppetized format and incorporated in the repos. In the future we can automate this if we have reason to trust the system.

**Comment by madeddie** [comment]
is this still an issue? :) should we close it?
