### ISSUE TITLE
ring-ping (irc): hide errors

### ISSUE THREAD

**Issue by Habbie** [NLNOG/nlnog-ring#44]
```
  job:  !ring-ping -6 2a02:ce0:9::e2f8:47ff:fe13:3836
nlnog:  2a02:ce0:9::e2f8:47ff:fe13:3836: 99 servers: 181ms average
nlnog:  2a02:ce0:9::e2f8:47ff:fe13:3836: unreachable from: boxed-it01
nlnog:  ssh connection failed: apnic01
```

If one node out of ~100 fails, I don't think that's very interesting to know for each ping. 

Proposal:
if less than x% (x=5?) of nodes are not responding (ssh connection failed etc.), just don't mention it at all, or perhaps just report a count on one of the first two lines, thus reducing noise.

**Comment by teunvink** [comment]
the ircbot implementation has changed a lot since this issue was opened, I'm closing this ticket.
