### ISSUE TITLE
Crash when -a -B encounters incomplete trace

### ISSUE THREAD

**Issue by rodecker** [NLNOG/nlnog-ring#60]
A broken path causes a crash when using -a and -B together:

pels@fizzix:~/Desktop$ ring-trace -R -6 -a -X -t png -n 0 -i as250net01 -B public01.infra.ring.nlnog.net
ring-trace v1.7.1 - written by Teun Vink teun@teun.tv
Including 1 hosts: as250net01
Performing ICMP traceroutes towards public01.infra.ring.nlnog.net from 1 ring hosts, ssh-timeout is 10 seconds.
Traceback (most recent call last):
  File "/home/pels/bin/ring-trace", line 1320, in <module>
    ns.show_country, ns.remove_broken, ns.highlight_ixp, ns.remove_duplicate, ns.transparent)
  File "/home/pels/bin/ring-trace", line 765, in graph
    asns.insert(0, a[0])
IndexError: list index out of range

This is triggered by the unfinished traceroute:

artin@as250net01:~$ mtr --report www.ams-ix.net
HOST: as250net01                  Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 2001:4ce8:fbb0::f128       0.0%    11    0.1   0.2   0.1   1.6   0.5
  2.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0

When using only -a or only -B no crash occurs.

**Comment by teunvink** [comment]
I believe this was fixed a long time ago.
